modLoader="javafml"
# The loader version doesn't matter. Modify the Forge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
license="MIT"

[[mods]]
modId="soulgravestone"
version="1.0.2"
displayName="Soul Gravestone"
displayURL="https://modrinth.com/mod/soul-gravestone"
logoFile="icon.png"
authors="nouho"
description='''Gravestone mod with ghost form on respawn'''

[[dependencies.soulgravestone]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.172,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soulgravestone]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.soulgravestone]]
    modId="curios"
    type="optional"
    versionRange="[9.5.1+1.21.1,)" # Specify an appropriate version range for Curios
    ordering="NONE"
    side="BOTH"
